"""Phase 1: what do the REAL detectors do on the provided demo clips? (read-only: no tuning, no incidents, nothing sent)

Replays data/demo/{fall,violence,snatch}.mp4 and the fire/crash sample clips through the same engine and the same
EventCapturePipeline as the live cameras (api/services/clip_replay.py), with ALL five detectors on every clip so
cross-triggers show. Evidence is written to a scratch folder; no incident is created; alerts are disabled.

    python scripts/demo_clips_check.py [--md docs/DEMO_CLIPS_CHECK.md] [--json out.json]
"""
import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
_tmp = tempfile.mkdtemp(prefix="ws-clipcheck-")
os.environ.update(INCIDENTS_DB_PATH=os.path.join(_tmp, "incidents.db"), EVIDENCE_ROOT_V2=os.path.join(_tmp, "evidence"),
                  LIVE_CAMERA_WORKERS_ENABLED="false", ALERTS_ENABLED="false", KMP_DUPLICATE_LIB_OK="TRUE",
                  TELEGRAM_BOT_TOKEN="", TELEGRAM_CHAT_ID="", OMNIDIM_API_KEY="", OMNIDIM_AGENT_ID="", SERPAPI_KEY="", DEMO_PHONE_NUMBER="")

from api.core.config import settings
from api.services.action_detectors import ACTION_NAMES
from api.services.clip_replay import replay_clip

CLIPS = [  # (clip, class it is for)
    ("data/demo/fall.mp4", "fall"),
    ("data/demo/violence.mp4", "violence"),
    ("data/demo/snatch.mp4", "snatch"),
    ("data/fire.mp4", "fire"),
    ("data/crash.mp4", "crash"),
]
ORDER = ["fall", "violence", "snatch", "fire", "crash"]


def fmt_signals(sig: dict) -> str:
    return ", ".join(f"{k}={v}" for k, v in sig.items() if k != "blocked_by") or "-"


def run() -> list:
    rows = []
    for rel, cls in CLIPS:
        path = ROOT / rel
        if not path.exists():
            rows.append({"clip": rel, "class": cls, "missing": True})
            continue
        print(f"replaying {rel} ...", flush=True)
        rep = replay_clip(path, "CAM-SAMPLE-003", action_names=ACTION_NAMES, fire_crash=True)
        rows.append({"clip": rel, "class": cls, "report": rep})
        for n in ORDER:
            d = rep.detectors.get(n)
            ev = rep.first_event(n)
            tag = "FIRED" if d and d["fired"] else "no"
            print(f"   {n:9s} {tag:6s} peak={d['peak_score'] if d else '-'} thr={d['threshold'] if d else '-'}"
                  f"{' first_event_at=%ss' % ev.start_s if ev else ''}{' (target class)' if n == cls else ''}", flush=True)
    return rows


def write_md(rows: list, path: Path) -> None:
    out = ["# Demo clips check: what the real detectors do on the provided clips",
           "",
           "**Tiny sample, one clip per class. Not accuracy.** Read-only: no tuning, no incidents created, nothing sent. Each clip was replayed through the real "
           "detectors and the same `EventCapturePipeline` as the live cameras (`api/services/clip_replay.py`, video time, sampling as live), with all five detectors "
           "enabled on every clip so cross-triggers are visible. Generated by `scripts/demo_clips_check.py`; the clips themselves are not part of the repository.",
           "",
           f"Thresholds in force: fall score {settings.FALL_SCORE_THRESHOLD}, violence CLIP {settings.VIOLENCE_CLIP_THRESHOLD}, snatch score {settings.SNATCH_SCORE_THRESHOLD}, "
           f"fire/crash floor {settings.FIRE_CRASH_CONFIDENCE_FLOOR}. 'Seconds to detect' is the video time at which the event was confirmed (N of M frames), from clip start.",
           ""]
    summary = ["| Clip | Class | Duration | Resolution / fps | Target detector fired | Peak score | Threshold | Seconds to detect | Cross-triggers |", "|---|---|---|---|---|---|---|---|---|"]
    detail = []
    for r in rows:
        if r.get("missing"):
            summary.append(f"| {r['clip']} | {r['class']} | missing | | | | | | |")
            continue
        rep = r["report"]
        d = rep.detectors.get(r["class"], {})
        ev = rep.first_event(r["class"])
        cross = [n for n in ORDER if n != r["class"] and rep.fired(n)]
        summary.append(f"| {r['clip']} | {r['class']} | {rep.duration_s} s | {rep.size[0]}x{rep.size[1]} @ {rep.fps} | **{'yes' if d.get('fired') else 'NO'}** | "
                       f"{d.get('peak_score', '-')} | {d.get('threshold', '-')} | {ev.start_s if ev else 'n/a'} | {', '.join(cross) or 'none'} |")
        detail.append(f"### {r['clip']} (target: {r['class']})")
        detail.append("")
        detail.append("| Detector | Fired | Peak score | Threshold | Events (video time) | Signals that fired / nearest miss | Blocked by |")
        detail.append("|---|---|---|---|---|---|---|")
        for n in ORDER:
            dd = rep.detectors.get(n)
            if dd is None:
                continue
            evs = [e for e in rep.events if e.detector == n]
            ev_txt = "; ".join(f"{e.start_s}-{e.end_s} s (peak {e.peak_score}, {e.confirmations})" for e in evs) or "-"
            sig = fmt_signals(evs[0].signals) if evs else fmt_signals(dd.get("near_miss_signals") or {})
            blocked = "; ".join(f"{b} (x{c})" for b, c in dd.get("blocked_by", [])[:3]) or "-"
            detail.append(f"| {n}{' (target)' if n == r['class'] else ''} | {'yes' if dd['fired'] else 'no'} | {dd['peak_score']} | {dd['threshold']} | {ev_txt} | {sig} | {blocked} |")
        if rep.quarantined:
            detail.append("")
            detail.append(f"Quarantined events: {rep.quarantined}")
        detail.append("")
    out += summary + [""] + detail
    out += ["Notes: signal values are scalar summaries; no keypoints are stored anywhere. For violence, 'peak score' is the highest CLIP cosine seen while the "
            "pose gates were open (0 means CLIP was never evaluated, i.e. a gate stayed closed); `blocked by` lists the gate or rule counts across evaluations."]
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--md", default=str(ROOT / "docs" / "DEMO_CLIPS_CHECK.md"))
    ap.add_argument("--json")
    args = ap.parse_args()
    rows = run()
    write_md(rows, Path(args.md))
    # Record which provided clips the real detector fired on (with each file's SHA-256): the dashboard enables a
    # demo trigger only for a clip that exists AND fired here (api/services/demo_clips.py).
    from api.services import demo_clips
    to_cat = {"fall": "fall", "violence": "assault", "snatch": "snatching"}
    record = {}
    for r in rows:
        if r["class"] in to_cat and not r.get("missing"):
            d = r["report"].detectors.get(r["class"], {})
            record[to_cat[r["class"]]] = {"fired": bool(d.get("fired")), "peak_score": d.get("peak_score"), "threshold": d.get("threshold")}
    demo_clips.save_record(record)
    print("recorded:", {k: v["fired"] for k, v in record.items()})
    if args.json:
        ser = []
        for r in rows:
            if r.get("missing"):
                ser.append(r); continue
            rep = r["report"]
            ser.append({"clip": r["clip"], "class": r["class"], "detectors": rep.detectors, "duration_s": rep.duration_s,
                        "events": [{k: v for k, v in e.__dict__.items() if k not in ("evidence", "incident")} for e in rep.events]})
        Path(args.json).write_text(json.dumps(ser, indent=1, default=str), encoding="utf-8")
    print(f"\nwrote {args.md}")


if __name__ == "__main__":
    main()
